addSbtPlugin("com.github.sbt" % "sbt-ci-release" % "1.5.11")
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.10.0")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.2.0")
addSbtPlugin("org.scalameta" % "sbt-mdoc" % "2.3.6" )
addSbtPlugin("io.kevinlee" % "sbt-docusaur" % "0.12.0")
addSbtPlugin("com.github.sbt" % "sbt-unidoc" % "0.5.0")
